#!/usr/bin/env python3
"""Can the resolving cell's own numeric parameters always clear the determinant?

Appendix B solves ``M K = -(N Lambda + c)`` for the carrier of the resolving
cell, and ``K = adj(M) rhs / det M`` has to be integral.  The second audit
showed that refining the lattice of ``Lambda`` cannot do this, because ``c``
collects parameters that are already fixed.

However the resolving cell's own non-carrier parameters are chosen at that very
moment, after ``det M`` is known, and they enter ``rhs`` linearly.  Writing
``v_p = (a_p, b_p)`` for the column of the token matrix at a non-carrier
parameter ``p``, and ``n_p in M Z`` for its numeric value, the reachable set of
``adj(M) rhs`` modulo ``d = |det M|`` is the subgroup of ``(Z/d)^2`` generated
by ``{ M adj(M) v_p mod d }``.  If that subgroup is everything, then whatever
the rest of ``rhs`` happens to be we can choose the ``n_p`` to make ``K``
integral, at the cost of restricting them to a coset of ``(M d Z)``, which
multiplies their box by ``d``.

This program decides that question for every family, token and chosen carrier
in the catalogue, for both the minimising carrier and, when it exists, a
carrier avoiding the head.

usage: carrier_integrality.py [CATALOGUE] [--lattice M]
"""
import argparse
import json
import math
import os
import sys
from itertools import combinations

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from carrier_determinants import token_vectors  # noqa: E402

DATA = os.path.normpath(os.path.join(HERE, "..", "data"))


def subgroup_is_everything(gens, d):
    """Do the given vectors generate all of (Z/d)^2?"""
    if d == 1:
        return True
    # the subgroup of (Z/d)^2 generated by `gens` is everything iff the
    # Smith normal form of the matrix whose rows are the generators together
    # with d*I has both invariant factors equal to 1, i.e. iff
    # gcd(all entries) == 1 and gcd(all 2x2 minors, d) == 1
    rows = [tuple(g) for g in gens] + [(d, 0), (0, d)]
    g1 = 0
    for r in rows:
        g1 = math.gcd(g1, math.gcd(r[0], r[1]))
    if g1 % d != 0 and math.gcd(g1, d) != 1:
        return False
    g2 = 0
    for r, s in combinations(rows, 2):
        g2 = math.gcd(g2, abs(r[0] * s[1] - r[1] * s[0]))
    return math.gcd(g2, d) == 1


def carriers(rows, npar, avoid=None):
    """(det, i, j) for every admissible carrier, best first."""
    a, b = rows[0], rows[1]
    out = []
    for i, j in combinations(range(npar), 2):
        if avoid is not None and avoid in (i, j):
            continue
        det = a[i] * b[j] - a[j] * b[i]
        if det:
            out.append((det, i, j))
    out.sort(key=lambda t: abs(t[0]))
    return out


def check(rows, npar, det, i, j, M):
    """Is the reachable subgroup all of (Z/|det|)^2?"""
    a, b = rows[0], rows[1]
    adj = ((b[j], -a[j]), (-b[i], a[i]))
    d = abs(det)
    gens = []
    for p in range(npar):
        if p in (i, j):
            continue
        v = (a[p], b[p])
        w = (M * (adj[0][0] * v[0] + adj[0][1] * v[1]),
             M * (adj[1][0] * v[0] + adj[1][1] * v[1]))
        gens.append((w[0] % d, w[1] % d))
    return subgroup_is_everything(gens, d), d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("catalogue", nargs="?",
                    default=os.path.join(DATA, "alphabet_families.json"))
    ap.add_argument("--lattice", type=int, default=24)
    a = ap.parse_args()
    cat = json.load(open(a.catalogue))
    tot = solvable_min = solvable_any = no_carrier = 0
    unimodular = 0
    bad = []
    for k in sorted(cat):
        for i, f in enumerate(cat[k].get("menu") or [cat[k]], 1):
            fam = f.get("family") or f
            if not isinstance(fam, dict) or "coefficients_by_label" not in fam:
                continue
            params = fam.get("parameters") or []
            npar = len(params)
            for tag, rows in token_vectors(fam):
                tot += 1
                cs = carriers(rows, npar)
                if not cs:
                    no_carrier += 1
                    continue
                if abs(cs[0][0]) == 1:
                    unimodular += 1
                    solvable_min += 1
                    solvable_any += 1
                    continue
                okmin, _ = check(rows, npar, *cs[0], a.lattice)
                solvable_min += okmin
                okany = any(check(rows, npar, *c, a.lattice)[0] for c in cs)
                solvable_any += okany
                if not okany:
                    bad.append(f"{k} menu{i} {tag}  dets {[abs(c[0]) for c in cs[:5]]}"
                               f"  params {params}")
    print(f"tokens examined                                   : {tot}")
    print(f"  with no admissible carrier                      : {no_carrier}")
    print(f"  unimodular carrier available (nothing to clear) : {unimodular}")
    print(f"  determinant clearable at the MINIMISING carrier : {solvable_min}")
    print(f"  determinant clearable at SOME admissible carrier: {solvable_any}")
    print(f"  clearable at NO carrier                         : {len(bad)}")
    for b in bad[:25]:
        print("     ", b)
    json.dump(bad, open(os.path.join(DATA, "carrier_not_clearable.json"), "w"))
    return 0 if not bad else 1


if __name__ == "__main__":
    sys.exit(main())
